image: node:8.9.1
options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - curl ipinfo.io/ip
          - npm install
          - docker run -d -p 4444:4444 selenium/standalone-chrome
          - npm run web