image: qamassive/v2
options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - sh ./scripts/start.sh
          - netstat -plnt
          - npm install
          - npm install selenium-standalone
          - selenium-standalone install --version=3.4.0
          - selenium-standalone --version=3.4.0 start
          - npm run web
