image: 
  name: selenium/standalone-chrome
  #username: $docker_user
  #password: $docker_user_pwd
options:
  docker: true
pipelines:
  branches:
    update-pipelines:
          - step:
             caches:
              - node
             script:
              - yarn install
              - yarn run api
              - yarn run web
              - echo "I made a pipeline!"