image: qamassive/allpackages
options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - sh ./scripts/start.sh
          - apt-get install net-tools
          - netstat -plnt
          - npm install
          - npm install wdio-allure-reporter
          - npm run web