image: 
  name: massiveinteractive/qa-ci
  username: $docker_user
  password: $docker_user_pwd
options:
  docker: true
pipelines:
    default:
      - parallel:   
          - step:
              name: API Tests
              caches:
                - docker
                - node
              script:
                - yarn install
                - yarn run api-smoke-tests 
          - step:
              name: WEB Tests
              caches:
                - docker
                - node
              script:
                - yarn install
                - sh ./scripts/start.sh
                - yarn run web-smoke-tests
    branches:
      nightly:
        - parallel:   
            - step:
                name: API Tests
                caches:
                  - docker
                  - node
                script:
                  - yarn install
                  - yarn run api-pipelines 
            - step:
                name: WEB Tests
                caches:
                  - docker
                  - node
                script:
                  - yarn install
                  - sh ./scripts/start.sh
                  - yarn run web-pipelines