image: 
  name: massiveinteractive/qa-ci
  username: $docker_user
  password: $docker_user_pwd
options:
  docker: true
pipelines:
  branches:
    update-pipelines:
      - step:
          caches:
            - node
            - docker
          script:
            # - sh ./scripts/start.sh
            - selenium-standalone start
            - netstat -plnt
            - yarn install
            - yarn run web
            