# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9.1
options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - docker run --rm -ti qa-automation npm start
          - npm install
          - docker run -p 4444:4444 selenium/standalone-chrome