options:
  docker: true
pipelines:
  branches:
    ci:
      - step:
          name: Package HelmChart and Push to S3
          script:
            - export VERSION="v$(date "+%y%m%d-%H%M%S")"
            - echo "VERSION - ${VERSION}"
      - step:
          name: Build and Push Web Test Image to DockerHub
          services:
            - docker
          caches:
            - docker
          script:
            #define custom date-time version

            - echo "VERSION - ${VERSION}"
