options:
  docker: true
pipelines:
  branches:
    ci:
      - step:
          name: Build and Push Web Test Image to DockerHub
          services:
            - docker
          caches:
            - docker
          script:
            #define custom date-time version
            - export VERSION="v$(date "+%y%m%d-%H%M%S")"
            - echo "VERSION - ${VERSION}"
            - export IMAGE_NAME="massiveinteractive/qa-web:$VERSION"
            - docker login -u $docker_user -p $docker_user_pwd
            #build and push image with above version
            - docker build --build-arg "test/web/web.Dockerfile" -t $IMAGE_NAME test/web
            - docker push $IMAGE_NAME
