image: qamassive/allpackages
options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - npm install
          - docker run --rm -d -p 4444:4444 -p 5999:5999 qamassive/allpackages:latest
          - npm run web
          