image: qamassive/v2
options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - sh ./scripts/start.sh
          - netstat -plnt
          - npm install
          - npm install wdio-allure-reporter
          - npm run web
