image: 
  name: massiveinteractive/qa-ci
  username: $docker_user
  password: $docker_user_pwd
options:
  docker: true
pipelines:
  branches:
    update-pipelines:
      - step:
           caches:
                  - docker
                  - node
           script:
               - yarn install
      - parallel:   
          - step:
              script:
                  - yarn run api 
          - step:
                script:
                  - sh ./scripts/start.sh
                  - yarn run web