image: node:8.9.1
options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - dig +short myip.opendns.com @resolver1.opendns.com
          - npm install
          - docker run -d -p 4444:4444 selenium/standalone-chrome
          - npm run web