options:
  docker: true
pipelines:
  branches:
    ci:
      - step:
          name: Package HelmChart and Push to S3
          image:
            name: jakexks/kubectl-helm-aws
          #   username: $docker_user
          #   password: $docker_user_pwd
          # services:
          #   - docker
          caches:
            - docker
          script:
            # - aws configure set AWS_ACCESS_KEY_ID AKIAIE7TXRZ3BAQTKJRQ
            # - aws configure set AWS_SECRET_ACCESS_KEY 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
            # - aws configure set AWS_DEFAULT_REGION ap-southeast-2
            # - aws configure set AWS_REGION ap-southeast-2
            # - aws configure set AWS_DEFAULT_OUTPUT text
            - sh deployment/scripts/AWSconfig.sh
            # - helm init --client-only
            # - helm package --version 0.1.0 test/web/helmchart
            # - helm s3 init s3://helm-job/helmchart
            # - helm repo add helmchart s3://helm-job/helmchart
            # - helm s3 push ./helmchart-0.1.0.tgz helmchart
            - sh deployment/scripts/helmS3push.sh
      - step:
          name: Build and Push Web Test Image to DockerHub
          services:
            - docker
          caches:
            - docker
          script:
            #define custom date-time version
            - export VERSION="v$(date "+%y%m%d-%H%M%S")"
            - echo "VERSION - ${VERSION}"
            - export IMAGE_NAME="massiveinteractive/qa-web:$VERSION"
            - docker login -u $docker_user -p $docker_user_pwd
            #build and push image with above version
            - docker build --build-arg Version=$VERSION -t $IMAGE_NAME test/web
            - docker push $IMAGE_NAME
