image: 
  name: massiveinteractive/qa-ci
  username: $docker_user
  password: $docker_user_pwd
options:
  docker: true
pipelines:
  branches:
    update-pipelines:
      - parallel:
          - step:
             caches:
              - node
             script:
              - yarn install
              - yarn run api
          - step:
             caches:
              - node
             script:
              - sh ./scripts/start.sh
              - yarn install
              - yarn run web
              - echo "I made a pipeline!"
