image: abhimassive/foo:firsttry
options:
  docker: true
pipelines:
  branches:
    update-pipelines:
    - step:
        script:
          - sh ./scripts/start.sh
          - yarn install
          - yarn run api