image: 
  name: massiveinteractive/qa-ci
  username: $docker_user
  password: $docker_user_pwd
options:
  docker: true
pipelines:
  branches:
    update-pipelines:
    - parallel:
      - step:
          script:
            - yarn install
            - yarn run api
      - step:
          script:
            - sh ./scripts/start.sh
            - yarn install
            - yarn run web