image: 
  name: massiveinteractive/qa-ci
  username: $docker_user
  password: $docker_user_pwd
options:
  docker: true
pipelines:
  branches:
    update-pipelines:
      - parallel:   
          - step:
              caches:
                - docker
                - node
              script:
               - yarn install
               - yarn run api 
          - step:
              caches:
                - docker
                - node
              script:
               - yarn install
               - sh ./scripts/start.sh
               - yarn run web