image: 
  name: massiveinteractive/qa-ci
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
options:
  docker: true
pipelines:
  branches:
    update-pipelines:
    - step:
        script:
          - sh ./scripts/start.sh
          - yarn install
          - yarn run api