orca: 
  base: "https://appcurator.io/api/orca"
  # base: "https://api.appcurator.com/"

web:
  path: "/sign-in"
  base: "https://appcurator.io" #IO
  # base: "https://my.appcurator.com" #(DEV-URL)
  # base: "https://squad-tenancy.web.appcurator.qa" #(QA-URL)

api:
  organizations: "https://hub.appcurator.io/org/api/v1/organizations/"
  identities: "http://a672f40ce2e4e11e88381023cadbc14f-717884523.ap-southeast-2.elb.amazonaws.com/api/identities/"
  memberships: "https://hub.appcurator.io/org/api/v1/memberships/"
  spaces: "https://hub.appcurator.io/spaces/v1/organizations/"
  token: "http://a672f40ce2e4e11e88381023cadbc14f-717884523.ap-southeast-2.elb.amazonaws.com/connect/token"
  keys: "https://hub.appcurator.io/keys/v1/keys"
  invites: "https://hub.appcurator.io/org/api/v1/invites/"