web:
  signIn: "//a[text() = 'Sign in']"
  emailInput: "//*[@type='email']"
  passwordInput: "//*[@type='password']"
  signInButton: "//button[@tabindex=0]"
  successMessage: "//h1"
  errorMessage: "//p[contains(@class,'caption')]"
  nameInput: "//input[@autocomplete='name']"  
  organizationInput: "//input[@autocomplete='organization']"
  submit: "//button[@type='submit']"
api:
  signIn: "/sign-in"
  signedIn: "/signed-in"
  createAccount: "/join"
  base: "https://my.appcurator.com"
  qabase: https://squad-tenancy.web.appcurator.qa
  organizations: "http://a549dbed120dc11e8a04b0a484309a38-1209232420.ap-southeast-2.elb.amazonaws.com/api/v1/organizations/"
  identities: "http://ab8b12ebc1c3211e8be6802ab3140617-1015176283.ap-southeast-2.elb.amazonaws.com/api/v1/identities/"
  memberships: "http://a8ab481632bd411e88381023cadbc14f-1381975742.ap-southeast-2.elb.amazonaws.com/api/memberships/"
