web:
  signIn: "//a[text() = 'Sign in']"
  emailInput: "//input[@type='email']"
  passwordInput: "//input[@type='password']"
  signInButton: "//button[@tabindex=0]"
  signInMessage: "//h1"
  nameInput: "//input[@autocomplete='name']"  
  organisationInput: "//input[@autocomplete='organisation']"
  createAccountButton: "//button[@type='submit']"
api:
  signIn: "/sign-in"
  signedIn: "/signed-in"
  createAccount: "/join"
  base: "https://my.appcurator.com"
  organizations: "http://ad94f3f9c0d6511e88a490a50eecb260-2119754876.ap-southeast-2.elb.amazonaws.com/"
  memberships: "http://adfe68990105811e89a1e067230e5e2d-1425011611.ap-southeast-2.elb.amazonaws.com/"
  identities: "http://aa568e86c0d5311e89a1e067230e5e2d-632874240.ap-southeast-2.elb.amazonaws.com/"