web:
  signIn: "//a[text() = 'Sign in']"
  emailInput: "//input[@type='email']"
  passwordInput: "//input[@type='password']"
  signInButton: "//button[@tabindex=0]"
  successMessage: "//h1"
  errorMessage: "//p[contains(@class,'caption')]"
  nameInput: "//input[@autocomplete='name']"  
  organizationInput: "//input[@autocomplete='organization']"
  submit: "//button[@type='submit']"
api:
  signIn: "/sign-in"
  signedIn: "/signed-in"
  createAccount: "/join"
  base: "https://my.appcurator.com"
  organizations: "http://a31e2a5f81c1c11e89f7706893e2f881-1946902899.ap-southeast-2.elb.amazonaws.com/api/v1/organizations/"
  identities: "http://ab8b12ebc1c3211e8be6802ab3140617-1015176283.ap-southeast-2.elb.amazonaws.com/api/v1/identities/"
  memberships: "http://a37f920111c2d11e89f7706893e2f881-620225296.ap-southeast-2.elb.amazonaws.com/api/memberships/"
