apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"zalenium","app.kubernetes.io/instance":"zalenium","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"zalenium","chart":"zalenium-0.0.1","helm.sh/chart":"zalenium-0.0.1","heritage":"Tiller","release":"zalenium","role":"grid"},"name":"zalenium","namespace":"moon"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"zalenium","app.kubernetes.io/name":"zalenium"}},"template":{"metadata":{"annotations":null,"labels":{"app":"zalenium","app.kubernetes.io/instance":"zalenium","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"zalenium","chart":"zalenium-0.0.1","helm.sh/chart":"zalenium-0.0.1","heritage":"Tiller","release":"zalenium","role":"grid"}},"spec":{"containers":[{"args":["start"],"env":[{"name":"ZALENIUM_KUBERNETES_CPU_REQUEST","value":"250m"},{"name":"ZALENIUM_KUBERNETES_CPU_LIMIT","value":"1000m"},{"name":"ZALENIUM_KUBERNETES_MEMORY_REQUEST","value":"500Mi"},{"name":"ZALENIUM_KUBERNETES_MEMORY_LIMIT","value":"2Gi"},{"name":"DESIRED_CONTAINERS","value":"2"},{"name":"MAX_DOCKER_SELENIUM_CONTAINERS","value":"10"},{"name":"SELENIUM_IMAGE_NAME","value":"elgalu/selenium"},{"name":"VIDEO_RECORDING_ENABLED","value":"false"},{"name":"SCREEN_WIDTH","value":"1440"},{"name":"SCREEN_HEIGHT","value":"900"},{"name":"MAX_TEST_SESSIONS","value":"1"},{"name":"NEW_SESSION_WAIT_TIMEOUT","value":"600000"},{"name":"DEBUG_ENABLED","value":"false"},{"name":"SEND_ANONYMOUS_USAGE_INFO","value":"true"},{"name":"TZ","value":"AEDT"},{"name":"KEEP_ONLY_FAILED_TESTS","value":"false"},{"name":"RETENTION_PERIOD","value":"3"},{"name":"CONTEXT_PATH","value":"/"}],"image":"dosel/zalenium:3","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/grid/console","port":4444},"initialDelaySeconds":90,"periodSeconds":5,"timeoutSeconds":1},"name":"zalenium","ports":[{"containerPort":4444,"protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/grid/console","port":4444},"timeoutSeconds":1},"resources":{"requests":{"cpu":"500m","memory":"500Mi"}},"volumeMounts":[{"mountPath":"/home/seluser/videos","name":"zalenium-videos"},{"mountPath":"/tmp/mounted","name":"zalenium-data"}]}],"serviceAccountName":"zalenium","volumes":[{"emptyDir":{},"name":"zalenium-videos"},{"emptyDir":{},"name":"zalenium-data"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: zalenium
    app.kubernetes.io/instance: zalenium
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: zalenium
    chart: zalenium-0.0.1
    helm.sh/chart: zalenium-0.0.1
    heritage: Tiller
    release: zalenium
    role: grid
  name: zalenium-yaml
  selfLink: /apis/extensions/v1beta1/namespaces/moon/deployments/zalenium
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: zalenium
      app.kubernetes.io/name: zalenium
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zalenium
        app.kubernetes.io/instance: zalenium
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: zalenium
        chart: zalenium-0.0.1
        helm.sh/chart: zalenium-0.0.1
        heritage: Tiller
        release: zalenium
        role: grid
    spec:
      containers:
        - args:
            - start
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: 250m
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: 1000m
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: 500Mi
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: 1Gi
            - name: DESIRED_CONTAINERS
              value: "1"
            - name: MAX_DOCKER_SELENIUM_CONTAINERS
              value: "10"
            - name: SELENIUM_IMAGE_NAME
              value: elgalu/selenium
            - name: VIDEO_RECORDING_ENABLED
              value: "true"
            - name: SCREEN_WIDTH
              value: "1280"
            - name: SCREEN_HEIGHT
              value: "960"
            - name: MAX_TEST_SESSIONS
              value: "1"
            - name: NEW_SESSION_WAIT_TIMEOUT
              value: "600000"
            - name: DEBUG_ENABLED
              value: "false"
            - name: SEND_ANONYMOUS_USAGE_INFO
              value: "false"
            - name: TZ
              value: Australia/Sydney
            - name: KEEP_ONLY_FAILED_TESTS
              value: "false"
            - name: RETENTION_PERIOD
              value: "1"
            - name: CONTEXT_PATH
              value: /
          image: dosel/zalenium:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /grid/console
              port: 4444
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: zalenium
          ports:
            - containerPort: 4444
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /grid/console
              port: 4444
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/seluser/videos
              name: zalenium-videos
            - mountPath: /tmp/mounted
              name: zalenium-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zalenium
      serviceAccountName: zalenium
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: zalenium-videos
        - emptyDir: {}
          name: zalenium-data
status: {}
