FROM node:8.10.0-slim AS build-deps

COPY package.json /tmp/package.json
RUN cd /tmp && yarn install
RUN mkdir -p /usr/src/app && cp -a /tmp/node_modules /usr/src/app/

WORKDIR /usr/src/app
COPY . /usr/src/app/
COPY ./scripts/test.sh /
COPY ./scripts/start.sh /

ENTRYPOINT ["/bin/bash"]
#CMD ["scripts/test.sh"]
